name: Build iOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # يتيح لك تشغيل البناء يدوياً من واجهة غيتهاب

jobs:
  build-ios:
    runs-on: macos-latest # هذا الشرط يجبر غيتهاب على استخدام جهاز ماك

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Build iOS App
        # أضفنا --module-name app ليتطابق مع هيكلة التشغيل لديك
        run: flet build ipa --module-name app

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: Riso_CPC_iOS
          path: build/ios/ipa/*.ipa